on:
  push:
    tags:
    - 'v*'
name: Create Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get permission for gradle wrapper
        run: chmod a+x ./gradlew
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Generate jar 
        run: ./gradlew bootJar
      - name: Generate documentation
        run: ./gradlew asciidoctor
      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title : ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            build/libs/*.jar
            build/docs/asciidocPdf/*.pdf